# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.CharField(max_length=5),
        ),
    ]
